appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: d+/jMpirTvFi+j51RkXPtVcbVlLznaKWpeOOo6av/I47buCXUo3F/1cYYyUg6GAvPySiiao2hZPWGBWb7Uykh3Qn4OAAItm2ntS2MLyW6k8FT6jeMPZyisgttyVE4/szOp3oYbLEHPnkyH6sPtYW+VZePMsLmHZfd+0TWc21MVEDUF2y3Y+cZ4rNh1zoOoe/NXxZdqg/LWDxNci4Dj9/amYAChTCwmciLnI19cy1XJPUCCApx9ySMiWcJMl51k+TlMm102e0ucJp9+VytW9B/Hdxs5izP+WwX381adJJeOm7ZppzgQVCiDkrBvqOrZ0Erk30gpW5LOSwSFQKa5oTYlbyDlKMLH/Ch7Qnlflbd1a3jlrd8lademICDKV0Ry7QJFwu3Xx2PXVy+p2cEnSoUwxDp4GWgKin7XN/xeFsyciyV6ibcO+ANzF5GFfUNppeu00MddIcVoA5UfMUvcr4fEuIVFHOqutvREXMZUK2yhSMYZaU2ysodZXxx5+G08Cg5cC3kRi7TCc/d+jvs1Ph9rF0C6nUtuHxR/rCtoPJ443oxJkQuqPqZwIsQ5eS88P1JFYIvEhCDHyU6gMneJ3JzwArGuRzp44DRksoZKnLw42BrD7oDsLD6c/t8SbfyLfeQ5ug+ZYVM+Wz072bgjXEhsIkYpL7lQD48kBx9X5iMU0=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: true
